# Generated by Django 4.2.5 on 2023-09-30 06:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_product_category'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='iamge',
            new_name='image',
        ),
    ]
