# Generated by Django 4.2.5 on 2023-11-02 07:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_rename_iamge_product_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'verbose_name_plural': 'products'},
        ),
    ]
